### ISSUE TITLE
Songs not matching

### ISSUE THREAD

**Issue by Eric-sson** [jjdenhertog/spotify-to-plex#1]
Thanks for creating this! I tried it with the same playlist and now only 2 songs are not matching.
So this is a big improvement.

https://open.spotify.com/playlist/37i9dQZF1DWSBi5svWQ9Nk

The below songs are in my library but are not being matched:

Mr. Belt & Wezol - It's Not Right But It's Okay
Claude - Écoutez-moi

My guess is that this has to do with some differences in spelling.

**Comment by jjdenhertog** [comment]
Awesome, in future releases there will be the option to tweak the search filters to allow for personal match preferences. It might also be worth looking into the metadata in Plex. I notice that sometimes plex has a difficulty matching tracks that have the same album title als track title.

**Comment by jjdenhertog** [comment]
@Eric-sson Can you run the test again with the newest update and share the Track Analyzer screenshot with me?

**Comment by Eric-sson** [comment]
@jjdenhertog 

I have some difficulties completing the below:

SPOTIFY_API_REDIRECT_URI=http://[ipaddress]:9030/api/spotify/token

Should I replace **[ipaddress]** with the IP Address of my unraid server?
Should I include the SPOTIFY_API_CLIENT_ID & SPOTIFY_API_CLIENT_SECRET somewhere in the redirect url?

**Comment by jjdenhertog** [comment]
@Eric-sson you need the IP address only if you want to connect your user as well. And in that case you need the IP address of how you are connecting with the service. This is a local ip address, something like 192.168.172.130.

So in that case it will be http://192.168.172.130:9030/api/spotify/token

It doesn't need to include the client or secret. But you do need to set the redirect url in the Spotify developers environment. I will update the documentation tomorrow.

But you don't need a valid redirect url for the scenario of simply manually adding playlists

**Comment by alexricher** [comment]
> So in that case it will be http://192.168.172.130:9030/api/spotify/token
> 
> It doesn't need to include the client or secret. But you do need to set the redirect url in the Spotify developers environment. I will update the documentation tomorrow.
> 
> But you don't need a valid redirect url for the scenario of simply manually adding playlists

Thanks for this info. 

For context, I use dockers compose and my env variable is `SPOTIFY_API_REDIRECT_URI=http://[IP_OF_PLEX_AND_STP]:9030/api/spotify/token`

Sadly, if I click on Users and "Connect Spotify Account", I login to Spotify and then, I get a page with: `INVALID_CLIENT: Invalid redirect URI`. It ends up not working.

What would be the next logical step?

**Comment by jjdenhertog** [comment]
@alexricher I have [updated](https://github.com/jjdenhertog/spotify-to-plex?tab=readme-ov-file#spotify-credentials) the documentation with some more info.
