### ISSUE TITLE
Feature request: Overview of songs missing from a playlist

### ISSUE THREAD

**Issue by Eric-sson** [jjdenhertog/spotify-to-plex#2]
Would it be possible to add an overview or a log file with the songs that were missing in your library after a playlist was synced?

**Comment by jjdenhertog** [comment]
@Eric-sson Great suggestion, I will make sure to add this in the next version.

**Comment by jjdenhertog** [comment]
Added this feature, find more info [here](https://github.com/jjdenhertog/spotify-to-plex/blob/main/README.md#missing-songs):
