### ISSUE TITLE
Limited to 200 songs per playlist

### ISSUE THREAD

**Issue by Eric-sson** [jjdenhertog/spotify-to-plex#3]
It looks like it will only grab the first batch of 200 songs. And not take another batch afterwards.
Below is an example playlist of 2000 songs:

https://open.spotify.com/playlist/1DTzz7Nh2rJBnyFbjsH1Mh

**Comment by jjdenhertog** [comment]
Plex is changing it's connection with Tidal. Which the current setup relies on. I'm hoping to have some time in december to restructure it. Then I will also add the syncing option and fix this issue.

**Comment by jjdenhertog** [comment]
I just rolled out a large update, it also solves this issue.
