### ISSUE TITLE
adding another user replaces the other user

### ISSUE THREAD

**Issue by capsel22** [jjdenhertog/spotify-to-plex#8]
Hi,

I am trying to add both of our Spotify users under the Users tab. However after pressing Add another user and authenticating with a second account it replaces the already configured account.
Happens the same in incognito when signing back with the first user, just replaces it.

Shouldn't be able to list both users?

Cheers.

**Comment by jjdenhertog** [comment]
@capsel22 I just pushed a new version, that should solve this issue. Could you try again?

**Comment by capsel22** [comment]
Yes that's resolved now now. Thank you so this super fast turn around. I will make sure to buy you a coffee when I'm back home.

**Comment by jjdenhertog** [comment]
> Yes that's resolved now now. Thank you so this super fast turn around. I will make sure to buy you a coffee when I'm back home.

@capsel22 It would also be a big help if you could help setting up the Unraid package. I create an issue for it:
https://github.com/jjdenhertog/spotify-to-plex/issues/9
